# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: jdscript # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs10.15
  region: ap-hongkong # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 128 # 内存大小，单位MB
  timeout: 900 # 超时时间，单位秒
  events: #触发器
    - timer: #签到
        parameters:
          name: beansign
          cronExpression: "0 0 0 * * * *"
          enable: true
          argument: jd_bean_sign
    - timer: #东东超市兑换奖品 #摇京豆 #京东汽车兑换
        parameters:
          name: blueCoin_clublottery_carexchange
          cronExpression: "0 0 0 * * * *"
          enable: true
          argument: jd_blueCoin&jd_club_lottery&jd_car_exchange
    - timer: #东东农场 #东东萌宠 #口袋书店 #京喜农场 #京东极速版签到 #京东家庭号 #金榜创造营 #明星小店
        parameters:
          name: fruit_pet_bookshop_jxnc_speedsign_family_goldcreator_starshop
          cronExpression: "0 5 6-18/6,8 * * * *"
          enable: true
          argument: jd_fruit&jd_pet&jd_bookshop&jd_jxnc&jd_speed_sign&jd_family&jd_gold_creator&jd_star_shop
    - timer: #宠汪汪 #摇钱树 #京东种豆得豆 #京喜工厂 #东东工厂 #电竞经理
        parameters:
          name: joy_moneyTree_plantBean_dreamFactory_jdfactory_EsportsManager
          cronExpression: "0 3 */1 * * * *"
          enable: true
          argument: jd_joy_new&jd_moneyTree&jd_plantBean&jd_dreamFactory&jd_jdfactory&jd_EsportsManager
    - timer: #宠汪汪积分兑换京豆 #签到领现金 #东东小窝 #京喜财富岛 #京东直播 #每日抽奖 #女装魔盒 #跳跳乐 #5G超级盲盒
        parameters:
          name: joyreward_cash_smallhome_cfd_live_dailylottery_nzmh_jump_mohe
          cronExpression: "0 0 0-16/8,20 * * * *"
          enable: true
          argument: jd_joy_reward_new&jd_cash&jd_small_home&jd_cfd&jd_live&jd_daily_lottery&jd_nzmh&jd_jump&jd_mohe
    - timer: #京东全民开红包 #进店领豆 #取关京东店铺商品 #京东抽奖机 #京东汽车 #京东秒秒币
        parameters:
          name: redPacket_shop_unsubscribe_lotteryMachine_car_ms
          cronExpression: "0 10 0 * * * *"
          enable: true
          argument: jd_redPacket&jd_shop&jd_unsubscribe&jd_lotteryMachine&jd_car&jd_ms
    - timer: #天天提鹅 #京喜牧场
        parameters:
          name: dailyegg_jxmc
          cronExpression: "0 8 */3 * * * *"
          enable: true
          argument: jd_daily_egg&jd_jxmc
    - timer: #东东超市 #十元街 #翻翻乐
        parameters:
          name: superMarket_syj_bigwinner
          cronExpression: "0 15 */1 * * * *"
          enable: true
          argument: jd_superMarket&jd_syj&jd_big_winner
    - timer: #京豆变动通知 #疯狂的joy #监控crazyJoy分红 #京东排行榜 #领京豆额外奖励 #京东保价 #闪购盲盒 #新潮品牌狂欢 #京喜领88元红包
        parameters:
          name: beanchange_crazyjoy_crazyjoybonus_rankingList_beanhome_price_sgmh_mcxhd_jxlhb
          cronExpression: "0 30 7 * * * *"
          enable: true
          argument: jd_bean_change&jd_crazy_joy&jd_crazy_joy_bonus&jd_rankingList&jd_bean_home&jd_price&jd_sgmh&jd_mcxhd&jd_jxlhb
    - timer: #金融养猪 #京东快递 #京东赚赚 #京东极速版红包 #领金贴
        parameters:
          name: pigPet_kd_jdzz_speedredpocke_jintie
          cronExpression: "0 3 1 * * * *"
          enable: true
          argument: jd_pigPet&jd_kd&jd_jdzz&jd_speed_redpocke&jd_jin_tie
  environment: #  环境变量
    variables: #  环境变量对象
      AAA: BBB # 不要删除，用来格式化对齐追加的变量的
